[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm ci",
  "npx playwright install --with-deps"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm run server"
